services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    env_file: .env
    environment:
      - CUDA_VISIBLE_DEVICES
      - JAX_PLATFORMS
      - DATASETS_ROOT_DIR=/datasets
      - WANDB_DIR=/wandb
    volumes:
      - .:/concept
      - ./bashrc_docker:/root/.bashrc
      - $DATASETS_ROOT_DIR:/datasets
      - $WANDB_DIR:/wandb
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

